[package]
name = "valuepack"
version = "0.1.0"
authors = ["sudeep"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.15"